### ISSUE TITLE
Consortia colleges not included

### ISSUE THREAD

**Issue by MargaretEG** [shilad/macademia#3]
Going from consortia home to a persons page the box in the top right does not contain any colleges.

**Comment by keeeeenw** [comment]
The issue may be related to changeCollegeString() function under lib.macademia.collegefiler.js

**Comment by keeeeenw** [comment]
Grails throws the following exception:

java.lang.RuntimeException: It looks like you are missing some calls to the r:layoutResources tag. After rendering your page the following have not been rendered: [defer]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:513)

**Comment by keeeeenw** [comment]
Fixed this by changing <r:script> into <script type="text/javascript"> inside the _collegeFilterDialog template
